"""Init complete schema: User, Team, Match, Prediction

Revision ID: 979d21af5881
Revises: 
Create Date: 2026-05-16 12:12:10.642708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979d21af5881'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('elo', sa.Float(), nullable=False),
    sa.Column('form_5', sa.Float(), nullable=False),
    sa.Column('avg_overall', sa.Float(), nullable=False),
    sa.Column('squad_value', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('odds_h', sa.Float(), nullable=True),
    sa.Column('odds_d', sa.Float(), nullable=True),
    sa.Column('odds_a', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    op.create_table('prediction_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('predicted_result', sa.String(length=1), nullable=False),
    sa.Column('prob_h', sa.Float(), nullable=False),
    sa.Column('prob_d', sa.Float(), nullable=False),
    sa.Column('prob_a', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_history')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
